version: '3.4.4'
services:
  eprintsdb:
    build:
      context: .
      dockerfile: eprintsdb.dockerfile
    ports:
      - "3306:3306"
    container_name: eprintsdb
    volumes:
      - mariadb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su=mysql", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 2s
      retries: 10
  eprintshttpd:
    build:
      context: .
      dockerfile: eprintshttpd.dockerfile
      args:
        EPRINTS_HOSTNAME: localhost
    ports:
      - "80:80"
    container_name: eprintshttpd
    volumes:
      - eprints:/usr/share/eprints
      - ./shared:/var/shared
    command: "httpd -k start -DFOREGROUND"
    depends_on:
      eprintsdb:
        condition: service_healthy
volumes:
  eprints:
  mariadb:
  shared: